select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue -- saving it as revenue
from customer 
group by gender -- this will let our business design the campaign better for each group

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
-- here we have to calculate the average review rating for each product and then find the top 5 products with highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- if the express shipping made the business more sales/money then our business should spend more money on faster deliveries 
select shipping_type, ROUND(AVG (purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers.
-- here we are checking the average purchase amount and total revenue between subsribers and non-subscribers,
-- this will tell if our subscriber business is working or not.
select subscription_status, COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend, 
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status 
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- here instead of looking at total discount we have to look at discount rate per product,
-- here we are trying to see which products heavily rely on discounts to sell.
select item_purchased,
ROUND (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- in this I have grouped the items and counted the number of times an item had discount (we are finding the percentage of times the discount was applied on an item)

-- Q7. Segement customers into new, Returning, and Loyal based on their total number of previous 
-- purchases, and show the count of each segment.
-- How can we segment customers, we need the definition of new, returning and loyal
-- Let's say if a customer bought something 1 time then they are new, if they bought something in between 2 - 10 times then
-- they are returning customers, if they bought items more than 10 times then they are loyal customers

-- here I will use CTE

with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category?
-- in this we would need a window function to rank products by total orders within each category. 
-- Then we will pick the top 3 and we will need CTE (Common Table Expression) for this query as well 
with item_counts as (
	select category,
	item_purchased,
	COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- we have used ROW_NUMBER window function here since we need different ranks. The rank and dense rank function will put the same number of total orders have same rank

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- This will tell if loyal customers are not subscribing that means the subscription offer that the business needs to be improved as many customers are not subscribing
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;


